import pytest
from ape import networks, accounts, project, Contract
import os
from eth_abi import encode
from eth_utils import keccak, encode_hex, decode_hex, to_checksum_address
from datetime import datetime, timedelta


# Define the contract address
CTF_ADDRESS=to_checksum_address("0x6F384Fec5eDEc49a7A6B6bC4b619A76197120B88")
USDC_ADDRESS =to_checksum_address("0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238")

def test_bet():
    # Define test users generated by hardhat (Already have a lot of token)
    user_a = accounts.test_accounts[0]
    user_b = accounts.test_accounts[1]

    # Define the usdc contract
    oz = project.dependencies["openzeppelin"]["5.0.0"]
    usdc_abi = oz.ERC20.contract_type  
    usdc = Contract(USDC_ADDRESS, contract_type=usdc_abi)

    # Define bet quantity
    amount = 10 * 10**6
    prob = 40 * 10**16

    # Give test users some gas money
    for acct in [user_a, user_b]:
        networks.active_provider.set_balance(acct.address, "10 ether")

    # Set the initial account balances for comparison after
    initial_balance_a = usdc.balanceOf(user_a.address)
    initial_balance_b = usdc.balanceOf(user_b.address)

    # Deploy the smart contract
    gambit = user_a.deploy(project.Gambit, CTF_ADDRESS, USDC_ADDRESS, gas_limit=2000000)

    # Define everything
    question_id = os.urandom(32)
    outcome_slot_count = 2
    oracle = to_checksum_address(user_a.address)
    end_timestamp = int((datetime.now() + timedelta(days=7)).timestamp())

    # Create bet
    print("Creating bet...")
    usdc.approve(gambit.address, amount, sender=user_a, gas_limit=2000000)
    gambit.createBet(amount, prob, question_id, end_timestamp, sender=user_a, gas_limit=2000000)

    bet = gambit.bets(question_id)
    assert bet.status == 0, f"Expected status 1, but got {bet.status}"
    assert bet.creator == user_a.address, f"Expected creator address {user_a.address}, but got {bet.creator}"

    print("✅ Bet created!")

    # Challenge bet
    print("Challenging bet...")
    usdc.approve(gambit.address, 15 * 10**6, sender=user_b, gas_limit=2000000)
    gambit.challengeBet(question_id, sender=user_b, gas_limit=2000000)

    bet = gambit.bets(question_id)
    assert bet.status == 1, f"Expected status 1, but got {bet.status}"
    assert bet.challenger == user_b.address, f"Expected challenger address {user_b.address}, but got {bet.challenger}"

    print("✅ Bet challenged!")

    # Ensure balances are reduced
    assert usdc.balanceOf(user_a.address) == initial_balance_a - (10 * 10**6)
    assert usdc.balanceOf(user_b.address) == initial_balance_b - (15 * 10**6)
    print("✅ User A and B balances updated correctly.")

    # Accept bet
    print("Confirming bet...") 
    gambit.confirmChallenge(question_id, True, sender=user_a, gas_limit=2000000)

    bet = gambit.bets(question_id)
    assert bet.status == 2, f"Expected status 2, but got {bet.status}"

    print("✅ Bet Accepted!")


def main():
    test_bet()
