import pytest
from ape import networks, accounts, project, Contract, chain
import os
from eth_abi import encode
from eth_utils import keccak, encode_hex, decode_hex, to_checksum_address
import time
from datetime import datetime, timedelta
from dotenv import load_dotenv
from enum import IntEnum

load_dotenv()

# Define the contract address
CTF_ADDRESS = to_checksum_address(os.getenv("CTF_ADDRESS"))
USDC_ADDRESS = to_checksum_address(os.getenv("USDC_ADDRESS"))
OO_ADDRESS = to_checksum_address(os.getenv("OO_ADDRESS"))


class BetStatus(IntEnum):
    ACCEPTING = 0
    ACTIVE = 1
    RESOLVING = 2
    RESOLVED = 3
    DISPUTED = 4
    ESCALATED = 5
    CANCELLED = 6


@pytest.mark.parametrize("amount, prob, duration, winningIndex", [
    (10 * 10**6, 60 * 10**16, 10, 0),
    (20 * 10**6, 40 * 10**16, 10, 1),
])
def test_bet_1_vs_1_agree(amount, prob, duration, winningIndex):
    # Define test users generated by hardhat (Already have a lot of token)
    user_a = accounts.test_accounts[0]
    user_b = accounts.test_accounts[1]
    # Define the usdc contract
    usdc = project.IERC20.at(USDC_ADDRESS)
    ctf = project.IConditionalTokens.at(CTF_ADDRESS)

    # Deploy the smart contract
    gambit = user_a.deploy(project.Gambit, CTF_ADDRESS, USDC_ADDRESS, OO_ADDRESS, 8, gas_limit=8000000)
    gambit.setupApproval(sender=user_a, gas_limit=8000000)

    # Set the initial account balances for comparison after
    initial_balance_a = usdc.balanceOf(user_a.address)
    initial_balance_b = usdc.balanceOf(user_b.address)

    # Define everything
    question_id = os.urandom(32)
    oracle = to_checksum_address(user_a.address)
    num_participants = 2
    end_timestamp = int((datetime.now() + timedelta(seconds=duration)).timestamp())

    # Create bet
    print("Creating bet...")
    usdc.approve(gambit.address, amount, sender=user_a, gas_limit=2000000)
    # probability and challenger lists are *not* parallel, but must be the same length
    # Probabilities are the pool probabilities a user can choose. The creator's probability should not be included
    # Challengers are the allowed permitted, limited to length 15. If it's empty, 
    gambit.createBet(question_id, amount, [user_b.address], [prob], end_timestamp, sender=user_a, gas_limit=2000000)

    bet = gambit.bets(question_id)
    participants = gambit.getParticipants(question_id, gas_limit=20000000)
    assert participants[0] == user_a.address, f"Expected creator address {user_a.address}, but got something else"
    assert bet.numParticipants == 2, f"Expected two participants, but got {bet.numParticipants}"

    print("✅ Bet created!")

    print("Joining bet...")
    creator_prob = 10**18 - prob
    participants = gambit.getParticipants(question_id, gas_limit=8000000)
    join_amount = (bet.amount * prob) // creator_prob
    usdc.approve(gambit.address, join_amount + 1, sender=user_b, gas_limit=8000000)

    gambit.joinBet(question_id, prob, sender=user_b, gas_limit=2000000)

    bet = gambit.bets(question_id)
    participants = gambit.getParticipants(question_id, gas_limit=20000000)
    assert participants[0] == user_a.address, f"Expected creator address {user_a.address}, but got something else"
    assert participants[1] == user_b.address, f"Expected the single challenger address {user_b.address}, but got something else"

    print("✅ Bet challenged!")

    # Ensure balances are reduced
    assert usdc.balanceOf(user_a.address) == initial_balance_a - amount
    assert usdc.balanceOf(user_b.address) == initial_balance_b - join_amount
    print("✅ User A and B balances updated correctly!")

    target_timestamp = bet.endTimeStamp + 10
    chain.pending_timestamp = target_timestamp
    chain.mine()

    chain_now = networks.active_provider.get_block("latest").timestamp

    print(f"Contract End Time: {datetime.fromtimestamp(bet.endTimeStamp)}")

    print(f"Chain 'Now' Time:  {datetime.fromtimestamp(chain_now)}")

    print("Waiting for bet duration to end...\n")
    while end_timestamp + 3 > int(datetime.now().timestamp()):
        print(".", end="")
        time.sleep(1)
    
    print(f"\n{datetime.now()}")
    print(f"{datetime.fromtimestamp(bet.endTimeStamp)}")

    # Vote on the winner
    winner = participants[winningIndex]
    print(bet.conditionId)
    slots = ctf.getOutcomeSlotCount(bet.conditionId)
    print(f"CTF QuestionID: {question_id.hex()}")
    print(f"Slots registered: {slots}")

    assert slots == bet.numParticipants, "CTF does not have this condition prepared!"

    print("User A voting on outcome...")
    assert bet.status == BetStatus.ACTIVE
    gambit.voteOnOutcome(bet.questionId, winner, sender=user_a, gas_limit=8000000)
    bet = gambit.bets(question_id)
    assert bet.status == BetStatus.RESOLVING
    print("✅ User A voted successfully!")

    print("User B voting on outcome...")
    gambit.voteOnOutcome(bet.questionId, winner, sender=user_b, gas_limit=8000000)
    bet = gambit.bets(question_id)
    assert bet.status == BetStatus.RESOLVED, f"Expected RESOLVED (BetStatus.RESOLVED), but got {bet.status}"
    print("✅ User B voted successfully!")
